import type { Config } from 'tailwindcss'
const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: '#1A73E8',
        danger: '#FF3B30',
        police: '#007AFF',
        accident: '#FF9500',
        repair: '#8E8E93',
        bg: '#F8F9FA',
        dark: '#0A0A0A',
        ink: '#101828',
        road: '#8A8A8A',
        beige: '#F5F1E8',
        mint: '#D9DFCC',
        orange: '#FF6A00',
        yellow: '#E8FF59',
      },
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        mono: ['Fragment Mono', 'monospace'],
        serif: ['Instrument Serif', 'serif'],
      },
      backdropBlur: { xl: '24px', '2xl': '32px' },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-ring': 'pulseRing 2s cubic-bezier(0.215,0.61,0.355,1) infinite',
        'dash-flow': 'dashFlow 0.9s linear infinite',
        'shimmer': 'shimmer 1.2s ease-in-out infinite',
        'border-spin': 'borderSpin 6s linear infinite',
        'car-drive': 'carDrive 6s linear infinite',
        'blob-drift': 'blobDrift 12s ease-in-out infinite',
        'waveform': 'waveform 0.6s ease-in-out infinite',
        'spin-slow': 'spin 22s linear infinite',
        'fade-up': 'fadeUp 0.7s cubic-bezier(0.16,1,0.3,1) forwards',
        'spring-in': 'springIn 0.5s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'gradient-shift': 'gradientShift 12s ease infinite',
        'video-drift': 'videoDrift 18s ease-in-out infinite',
        'mesh-pan': 'meshPan 20s linear infinite',
        'noise-shift': 'noiseShift 0.2s steps(1) infinite',
      },
      keyframes: {
        float: { '0%,100%': { transform: 'translateY(0px) rotateX(8deg)' }, '50%': { transform: 'translateY(-18px) rotateX(2deg)' } },
        pulseRing: { '0%': { transform: 'scale(0.6)', opacity: '1' }, '100%': { transform: 'scale(2.2)', opacity: '0' } },
        dashFlow: { '0%': { strokeDashoffset: '30' }, '100%': { strokeDashoffset: '0' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        borderSpin: { '0%': { '--angle': '0deg' }, '100%': { '--angle': '360deg' } },
        carDrive: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        blobDrift: { '0%,100%': { borderRadius: '60% 40% 30% 70%/60% 30% 70% 40%' }, '50%': { borderRadius: '30% 60% 70% 40%/50% 60% 30% 60%' } },
        waveform: { '0%,100%': { scaleY: '0.3' }, '50%': { scaleY: '1' } },
        fadeUp: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        springIn: { '0%': { opacity: '0', transform: 'scale(0.8)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        gradientShift: { '0%,100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        videoDrift: { '0%,100%': { transform: 'translate(0,0) scale(1.05)' }, '33%': { transform: 'translate(-1%,-1%) scale(1.08)' }, '66%': { transform: 'translate(1%,0.5%) scale(1.06)' } },
        meshPan: { '0%': { transform: 'translate(0,0)' }, '100%': { transform: 'translate(-50%,-50%)' } },
        noiseShift: { '0%': { transform: 'translate(0,0)' }, '25%': { transform: 'translate(-5%,-5%)' }, '50%': { transform: 'translate(-10%,5%)' }, '75%': { transform: 'translate(5%,-10%)' }, '100%': { transform: 'translate(0,0)' } },
      },
      boxShadow: {
        'soft': '0 4px 20px rgba(0,0,0,0.08)',
        'lift': '0 8px 30px rgba(0,0,0,0.12)',
        'glow-blue': '0 0 20px rgba(26,115,232,0.4)',
        'glow-red': '0 0 20px rgba(255,59,48,0.4)',
        'glass': '0 8px 32px rgba(0,0,0,0.08), inset 0 1px 0 rgba(255,255,255,0.5)',
      },
    },
  },
  plugins: [],
}
export default config
