'use client';
import { useEffect, useRef, useState } from 'react';
import { reportTypes, AZ_BOUNDS } from '../../constants/map';
type Flow='idle'|'selectType'|'selectLocation'|'photos'|'describe'|'thanks'|'nearbyCheck';
const markerSvgs:any={
roadwork:`<svg width="20" height="20" viewBox="0 0 32 32" fill="none"><path d="M8 21.5 L24 21.5 L21.2 9 H10.8 L8 21.5Z" fill="#FF8C32" stroke="#1a1a1a" stroke-width="1.4"/><path d="M12 14 H20" stroke="white" stroke-width="1.6"/></svg>`,
accident:`<svg width="20" height="20" viewBox="0 0 32 32" fill="none"><path d="M16 5 L26 24 H6 L16 5Z" fill="#FF4A4A" stroke="#1a1a1a" stroke-width="1.4"/></svg>`,
closed:`<svg width="20" height="20" viewBox="0 0 32 32" fill="none"><rect x="6" y="9" width="20" height="5" rx="2.5" fill="#7C6CF0" stroke="#1a1a1a" stroke-width="1.2"/></svg>`,
water:`<svg width="20" height="20" viewBox="0 0 32 32" fill="none"><path d="M16 6 C11 12 7 15 7 19 C7 23 10.5 26 16 26 S25 23 25 19 C25 15 21 12 16 6Z" fill="#2D9CFF" stroke="#1a1a1a" stroke-width="1.3"/></svg>`,
pothole:`<svg width="20" height="20" viewBox="0 0 32 32" fill="none"><path d="M6 16 C8 10 12 8 16 8 S24 10 26 16 C24 22 20 24 16 24 S8 22 6 16Z" fill="#8B7355" stroke="#1a1a1a" stroke-width="1.3"/></svg>`,
police:`<svg width="20" height="20" viewBox="0 0 32 32" fill="none"><rect x="8" y="12" width="16" height="8" rx="2.5" fill="#1a1a1a"/></svg>`,
construction:`<svg width="20" height="20" viewBox="0 0 32 32" fill="none"><path d="M7 24 V10 H11 V24" fill="#FFD93D" stroke="#1a1a1a" stroke-width="1.2"/></svg>`,
light:`<svg width="20" height="20" viewBox="0 0 32 32" fill="none"><rect x="11.5" y="5" width="9" height="18" rx="4.5" fill="#2D2D2D" stroke="#1a1a1a" stroke-width="1.2"/></svg>`,
};
function distance(a:any,b:any){const R=6371000;const dLat=(b.lat-a.lat)*Math.PI/180;const dLng=(b.lng-a.lng)*Math.PI/180;const la1=a.lat*Math.PI/180;const la2=b.lat*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
export default function MapView(){
const mapRef=useRef<any>(null);const containerRef=useRef<HTMLDivElement>(null);const userMarkerRef=useRef<any>(null);const trailRef=useRef<[number,number][]>([]);const watchIdRef=useRef<any>(null);
const [flow,setFlow]=useState<Flow>('idle');const [selectedType,setSelectedType]=useState<any>(null);const [selectedLatLng,setSelectedLatLng]=useState<any>(null);
const [photos,setPhotos]=useState<(string|null)[]>([null,null,null]);const [desc,setDesc]=useState('');const [userTrail,setUserTrail]=useState<any[]>([]);const [nearbyReport,setNearbyReport]=useState<any>(null);
const [softMode,setSoftMode]=useState('ultra');const [searchQuery,setSearchQuery]=useState('');const [searchResults,setSearchResults]=useState<any[]>([]);const [timeFilter,setTimeFilter]=useState('all');
const [markers,setMarkers]=useState<any[]>(()=>{try{const s=typeof window!=='undefined'?localStorage.getItem('baku_markers_v8'):null;if(s) return JSON.parse(s);}catch{}return [{lat:40.4093,lng:49.8671,type:'roadwork',time:Date.now()-1200000,confirms:3,id:'1'},{lat:40.415,lng:49.872,type:'accident',time:Date.now()-3900000,confirms:1,id:'2'},{lat:40.405,lng:49.86,type:'closed',time:Date.now()-12000000,confirms:5,id:'3'},{lat:40.418,lng:49.865,type:'water',time:Date.now()-600000,confirms:2,id:'4'}];});
useEffect(()=>{try{localStorage.setItem('baku_markers_v8', JSON.stringify(markers));}catch{}},[markers]);
const locateUser=(continuous=false)=>{
if(typeof window==='undefined'||!navigator.geolocation) return;
if(continuous){
if(watchIdRef.current) navigator.geolocation.clearWatch(watchIdRef.current);
watchIdRef.current=navigator.geolocation.watchPosition((pos)=>{
const cur={lat:pos.coords.latitude,lng:pos.coords.longitude};setUserTrail(prev=>{const next=[...prev,cur].slice(-120);trailRef.current=next.map(p=>[p.lng,p.lat] as [number,number]);if(mapRef.current){const src=mapRef.current.getSource('trail');if(src) src.setData({type:'Feature', geometry:{type:'LineString', coordinates: trailRef.current}, properties:{}});}return next;});
if(mapRef.current){const el=document.createElement('div');el.innerHTML=`<div style="width:22px;height:22px;background:#2D7CFF;border-radius:50%;border:3.5px solid white;box-shadow:0 0 0 6px rgba(45,124,255,0.18)"></div>`;if(!userMarkerRef.current){const {Marker}=require('maplibre-gl');userMarkerRef.current=new Marker({element: el.firstChild as HTMLElement}).setLngLat([cur.lng, cur.lat]).addTo(mapRef.current);}else userMarkerRef.current.setLngLat([cur.lng, cur.lat]);}
for(const rep of markers){const d=distance(cur,rep);if(d<35){setNearbyReport({...rep,dist:Math.round(d)});setFlow('nearbyCheck');break;}}
},()=>{},{enableHighAccuracy:true});
}else{
navigator.geolocation.getCurrentPosition((pos)=>{const cur={lat:pos.coords.latitude,lng:pos.coords.longitude};if(mapRef.current){mapRef.current.flyTo({center:[cur.lng,cur.lat],zoom:16});}},()=>{});
}
};
useEffect(()=>{
if(typeof window==='undefined') return;
let map:any=null;
const init=async ()=>{
const maplibregl=await import('maplibre-gl');
await import('maplibre-gl/dist/maplibre-gl.css');
if(!containerRef.current) return;
map=new maplibregl.Map({container: containerRef.current, style:'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json', center:[AZ_BOUNDS.center.lng, AZ_BOUNDS.center.lat], zoom:12.5, maxBounds:[[AZ_BOUNDS.west, AZ_BOUNDS.south],[AZ_BOUNDS.east, AZ_BOUNDS.north]] as any, attributionControl:false});
map.on('load', ()=>{
const canvas=map.getCanvas();canvas.style.filter=softMode==='ultra'?'saturate(0.42) brightness(1.08) contrast(0.88) sepia(0.04)':'saturate(0.72) brightness(1.02)';canvas.style.transition='filter 0.6s cubic-bezier(0.16,1,0.3,1)';
map.addSource('trail',{type:'geojson', data:{type:'Feature', geometry:{type:'LineString', coordinates:[]}, properties:{}}});
map.addLayer({id:'trail-line', type:'line', source:'trail', paint:{'line-color':'#2D7CFF','line-width':4,'line-opacity':0.28,'line-dasharray':[2,2]}});
setTimeout(()=>locateUser(true),800);
});
map.on('click',(e:any)=>{if((window as any).__bakuFlow==='selectLocation'){setSelectedLatLng({lat:e.lngLat.lat,lng:e.lngLat.lng});setFlow('photos');(window as any).__bakuFlow='photos';}});
mapRef.current=map;
};
init();
return ()=>{if(watchIdRef.current) navigator.geolocation.clearWatch(watchIdRef.current);if(map) map.remove();};
},[softMode]);
useEffect(()=>{if(typeof window!=='undefined')(window as any).__bakuFlow=flow;},[flow]);
useEffect(()=>{
if(!mapRef.current) return;
document.querySelectorAll('.baku-report-marker').forEach(el=>el.remove());
const filtered=markers.filter((m:any)=>{if(timeFilter==='2h') return Date.now()-m.time<7200000;if(timeFilter==='today') return Date.now()-m.time<86400000;return true;});
filtered.forEach(async (m:any)=>{
const maplibregl=await import('maplibre-gl');
const type=reportTypes.find((r:any)=>r.id===m.type);
const svg=markerSvgs[m.type]||markerSvgs['roadwork'];
const el=document.createElement('div');el.className='baku-report-marker';
el.innerHTML=`<div style="width:52px;height:52px;background:white;border-radius:50%;display:flex;align-items:center;justify-content:center;box-shadow:0 10px 28px rgba(0,0,0,0.18);border:1px solid #EDE8E3;position:relative;cursor:pointer"><div style="width:36px;height:36px;border-radius:50%;background:${type?.color||'#FFD6A5'};display:flex;align-items:center;justify-content:center">${svg}</div><div style="position:absolute;bottom:-4px;right:-2px;background:#1a1a1a;color:white;font-size:9px;padding:2px 5px;border-radius:10px;border:1.5px solid white">${m.confirms||0} ✓</div></div>`;
el.addEventListener('click', ()=>{setNearbyReport(m);setFlow('nearbyCheck');});
new maplibregl.Marker({element:el}).setLngLat([m.lng,m.lat]).addTo(mapRef.current);
});
},[markers,timeFilter]);
const searchStreet=async()=>{if(!searchQuery.trim()) return;try{const res=await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(searchQuery)}&countrycodes=az&viewbox=44.6,41.9,51.0,38.4&bounded=1&limit=5`);const data=await res.json();setSearchResults(data);if(data[0]&&mapRef.current) mapRef.current.flyTo({center:[parseFloat(data[0].lon),parseFloat(data[0].lat)],zoom:16});}catch{}};
const handleConfirm=(stillThere:boolean)=>{if(!nearbyReport) return;if(stillThere) setMarkers((prev:any)=>prev.map((m:any)=>m.id===nearbyReport.id?{...m,confirms:(m.confirms||0)+1,time:Date.now()}:m));else setMarkers((prev:any)=>prev.map((m:any)=>m.id===nearbyReport.id?{...m,confirms:Math.max(0,(m.confirms||0)-1)}:m));setFlow('idle');setNearbyReport(null);};
const handlePhoto=(idx:number,file:File)=>{const r=new FileReader();r.onload=()=>{const a=[...photos];a[idx]=r.result as string;setPhotos(a);};r.readAsDataURL(file);};
return (
<div className="relative w-full h-[100dvh] overflow-hidden bg-[#F2F0EB]">
<div ref={containerRef} className="w-full h-full absolute inset-0 z-0"/>
<div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-[56px] pointer-events-none z-[400]"><div className="w-[52px] h-[52px] bg-white rounded-[18px] shadow-[0_16px_32px_rgba(0,0,0,0.18)] border border-[#EDE8E3] flex items-center justify-center"><svg width="28" height="16" viewBox="0 0 28 16" fill="none"><path d="M3 9 L5 4 H23 L25 9 Z" fill="#1a1a1a"/><circle cx="9" cy="10.5" r="1.8" fill="white" stroke="#1a1a1a" strokeWidth="1"/><circle cx="19" cy="10.5" r="1.8" fill="white" stroke="#1a1a1a" strokeWidth="1"/></svg></div>{userTrail.length>2 && <div className="mt-1 text-[9px] text-[#2D7CFF] bg-white/90 px-2 py-0.5 rounded-full border mx-auto w-fit">ИДЕТЕ • {userTrail.length}</div>}</div>
<div className="absolute top-0 left-0 right-0 z-[600] p-3 flex gap-2">
<div className="flex-1 max-w-[420px] bg-white/92 backdrop-blur-[20px] rounded-full border border-[#EDE8E3] shadow-[0_8px_24px_rgba(0,0,0,0.12)] flex items-center px-3"><input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&searchStreet()} placeholder="Поиск улицы в Баку..." className="flex-1 bg-transparent outline-none px-2.5 py-2.5 text-[13px]"/><button onClick={searchStreet} className="px-3 py-1.5 bg-[#1a1a1a] text-white rounded-full text-[11px] font-bold">Найти</button></div>
<button onClick={()=>setSoftMode(s=>s==='ultra'?'soft':'ultra')} className="w-10 h-10 bg-white/92 backdrop-blur rounded-full border border-[#EDE8E3] shadow flex items-center justify-center">👁️</button>
</div>
<div className="absolute top-[58px] left-3 z-[600] flex gap-2">{[{id:'all',label:'Все'},{id:'today',label:'Сегодня'},{id:'2h',label:'2 часа'}].map(f=><button key={f.id} onClick={()=>setTimeFilter(f.id)} className={`px-3 py-1.5 rounded-full text-[11px] font-bold border backdrop-blur ${timeFilter===f.id?'bg-[#1a1a1a] text-white border-black':'bg-white/85 text-black border-[#EDE8E3]'}`}>{f.label}</button>)}</div>
<div className="absolute bottom-[140px] right-3 z-[600] flex flex-col gap-2.5"><button onClick={()=>setFlow('selectType')} className="w-[56px] h-[56px] bg-[#1a1a1a] rounded-[18px] shadow-[0_16px_32px_rgba(0,0,0,0.32)] flex items-center justify-center text-white text-[26px]">+</button><button onClick={()=>locateUser(false)} className="w-[48px] h-[48px] bg-white rounded-[16px] shadow border border-black/5 flex items-center justify-center"><div className="w-5 h-5 rounded-full border-[2.5px] border-black flex items-center justify-center"><div className="w-1.5 h-1.5 bg-black rounded-full"/></div></button></div>
<div className="absolute bottom-0 left-0 right-0 z-[550] p-2.5 pb-[max(12px,env(safe-area-inset-bottom))]"><div className="mx-auto max-w-[820px] bg-white/92 backdrop-blur-[24px] rounded-[26px] shadow-[0_16px_48px_rgba(0,0,0,0.18)] border border-[#EDE8E3] p-2 flex items-center gap-2 overflow-x-auto scroll-hide"><div className="text-[9px] text-neutral-400">MapLibre • Positron GL • Google-like • без ключа • бесплатно навсегда • ULTRA SOFT • {softMode} • 60-120 FPS</div><div className="ml-auto text-[9px] text-[#2D7CFF] hidden md:block">ИДЕТЕ {userTrail.length} точек</div></div></div>
{flow==='selectType' && (<div className="absolute inset-0 z-[700] flex items-end justify-center"><div className="absolute inset-0 bg-black/15 backdrop-blur-[1px]" onClick={()=>setFlow('idle')}/><div className="relative w-full max-w-[580px] bg-white rounded-t-[32px] p-6 pb-[max(20px,env(safe-area-inset-bottom))] shadow-[0_-12px_48px_rgba(0,0,0,0.18)] mosh-slide-up"><h3 className="font-black text-[19px]">Что случилось?</h3><div className="grid grid-cols-2 gap-2.5 mt-4 max-h-[52vh] overflow-auto scroll-hide">{reportTypes.map((t:any)=><button key={t.id} onClick={()=>{setSelectedType(t);setFlow('selectLocation');}} className="p-3.5 rounded-[18px] border border-[#EDE8E3] bg-[#FCFCFA] text-left hover:bg-white active:scale-[0.98] transition-all"><div className="w-10 h-10 rounded-[11px] flex items-center justify-center mb-2" style={{background:t.color}}><span dangerouslySetInnerHTML={{__html:markerSvgs[t.id]}}/></div><p className="font-bold text-[12.5px]">{t.label}</p><p className="text-[10px] text-neutral-500 mt-0.5">{t.desc}</p></button>)}</div></div></div>)}
{flow==='selectLocation' && (<div className="absolute top-[52px] left-1/2 -translate-x-1/2 z-[700] w-[92%] max-w-[420px]"><div className="bg-[#1a1a1a] text-white px-4 py-3 rounded-full text-[12.5px] font-medium shadow-[0_12px_32px_rgba(0,0,0,0.28)] flex items-center justify-between"><span>Нажмите на карту чтобы выделить улицу 📍 Google-like</span><button onClick={()=>setFlow('selectType')} className="w-6 h-6 bg-white/15 rounded-full">✕</button></div>{searchResults.length>0 && <div className="mt-2 bg-white rounded-[16px] border border-[#EDE8E3] shadow p-2 max-h-[180px] overflow-auto">{searchResults.map((r:any,i:number)=><button key={i} onClick={()=>{if(mapRef.current) mapRef.current.flyTo({center:[parseFloat(r.lon),parseFloat(r.lat)],zoom:16});setSearchResults([]);}} className="w-full text-left p-2.5 rounded-[10px] hover:bg-[#F5F2EE] text-[12px]">{r.display_name.slice(0,80)}</button>)}</div>}</div>)}
{flow==='nearbyCheck' && nearbyReport && (<div className="absolute inset-0 z-[800] flex items-end justify-center p-3"><div className="w-full max-w-[520px] bg-white rounded-[28px] shadow-[0_24px_64px_rgba(0,0,0,0.28)] p-5 border border-[#EDE8E3] mosh-slide-up"><div className="flex items-start gap-3"><div className="w-12 h-12 rounded-[14px] flex items-center justify-center shrink-0" style={{background:reportTypes.find((r:any)=>r.id===nearbyReport.type)?.color}}><span dangerouslySetInnerHTML={{__html:markerSvgs[nearbyReport.type]}}/></div><div className="flex-1"><p className="font-black text-[15px]">{reportTypes.find((r:any)=>r.id===nearbyReport.type)?.label}</p><p className="text-[11px] text-neutral-500 mt-1">Вы в {nearbyReport.dist||0}м от этой точки • Идете пешком • Тропа {userTrail.length} точек • Google-like карта</p><div className="mt-2 flex items-center gap-2 text-[10px]"><span className="px-2 py-1 rounded-full bg-[#F5F2EE] border">{Math.floor((Date.now()-nearbyReport.time)/60000)} мин назад</span><span className="px-2 py-1 rounded-full bg-[#1a1a1a] text-white">{nearbyReport.confirms} ✓</span></div></div><button onClick={()=>{setFlow('idle');setNearbyReport(null);}} className="w-8 h-8 bg-[#F5F2EE] rounded-full">✕</button></div><div className="mt-5"><p className="text-[13px] font-bold text-center">Это все еще на месте? 🚩</p><p className="text-[11px] text-neutral-500 text-center mt-1">Вы проходите рядом, помогите проверить. Флажка покажет актуальность.</p><div className="mt-4 grid grid-cols-3 gap-2.5"><button onClick={()=>handleConfirm(true)} className="py-3.5 rounded-full bg-[#1a1a1a] text-white font-bold text-[13px] active:scale-[0.97]">Да, тут • 🚩</button><button onClick={()=>handleConfirm(false)} className="py-3.5 rounded-full bg-[#F5F2EE] border border-[#EDE8E3] font-bold text-[13px] active:scale-[0.97]">Нет, убрали</button><button onClick={()=>{navigator.clipboard.writeText('Baku Safe Map: '+nearbyReport.type);}} className="py-3.5 rounded-full bg-white border border-[#EDE8E3] font-bold text-[12px]">Шерить</button></div><div className="mt-3 flex items-center justify-between text-[10px] text-neutral-400"><span>Тропа: {userTrail.length} точек</span><button onClick={()=>setFlow('idle')} className="underline">Пропустить</button></div></div></div></div>)}
{flow==='photos' && (<div className="absolute inset-0 z-[800] bg-white flex flex-col text-black"><div className="p-5 border-b border-[#EDE8E3] flex items-center gap-3"><button onClick={()=>setFlow('selectLocation')} className="w-9 h-9 bg-[#F5F2EE] rounded-full">←</button><div><h3 className="font-bold text-[15px]">Фото</h3><p className="text-[11px] text-neutral-500">2 обязательно • Google-like</p></div></div><div className="flex-1 p-5 space-y-4 overflow-auto scroll-hide">{[0,1,2].map(i=><label key={i} className="flex h-[132px] border-2 border-dashed border-[#EDE8E3] rounded-[16px] items-center justify-center bg-[#FCFCFA] overflow-hidden cursor-pointer">{photos[i]?<img src={photos[i]!} className="w-full h-full object-cover"/>:<span className="text-[12px] text-neutral-400">Фото {i+1} {i<2?'*':''}</span>}<input type="file" accept="image/*" className="hidden" onChange={e=> e.target.files && handlePhoto(i,e.target.files[0])}/></label>)}<button onClick={()=>setFlow('describe')} disabled={!photos[0]||!photos[1]} className="w-full py-3.5 bg-[#1a1a1a] text-white rounded-full font-bold disabled:opacity-40">Далее • {photos.filter(Boolean).length}/3</button></div></div>)}
{flow==='describe' && (<div className="absolute inset-0 z-[800] bg-white flex flex-col text-black"><div className="p-5 border-b border-[#EDE8E3] flex items-center gap-3"><button onClick={()=>setFlow('photos')} className="w-9 h-9 bg-[#F5F2EE] rounded-full">←</button><div><h3 className="font-bold">Опишите</h3><p className="text-[11px] text-neutral-500">Кратко и вежливо</p></div></div><div className="flex-1 p-5"><textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Например: На Азадлыг 45 яма 10 см. Опасно." className="w-full h-[120px] bg-[#F5F2EE] rounded-[16px] p-4 text-[13px] outline-none resize-none" maxLength={300}/><p className="text-[10px] text-neutral-400 mt-2">{desc.length}/300</p><button onClick={()=>{if(desc.length<10) return alert('Подробнее');const id=Date.now().toString();const m={lat:selectedLatLng.lat,lng:selectedLatLng.lng,type:selectedType.id,time:Date.now(),confirms:0,id};setMarkers((prev:any)=>[...prev,m]);setFlow('thanks');}} className="mt-5 w-full py-3.5 bg-[#1a1a1a] text-white rounded-full font-bold">Отправить на проверку • Google-like</button></div></div>)}
{flow==='thanks' && (<div className="absolute inset-0 z-[900] bg-white flex flex-col items-center justify-center p-8 text-center text-black"><div className="w-16 h-16 bg-[#E5F3E8] rounded-full flex items-center justify-center text-2xl">✓</div><h3 className="font-black text-[20px] mt-5">Спасибо!</h3><p className="text-[12px] text-neutral-500 mt-2 max-w-[280px]">Добавили на Google-like карту • ULTRA SOFT • бесплатно навсегда</p><button onClick={()=>{setFlow('idle');setSelectedType(null);setSelectedLatLng(null);setPhotos([null,null,null]);setDesc('');}} className="mt-6 px-7 py-2.5 bg-[#1a1a1a] text-white rounded-full font-bold">К карте</button></div>)}
</div>
);
}
